AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # Lambda Function
  ProcessFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref RawEmailBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref POTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CompletedTable
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          RAW_EMAIL_BUCKET: !Ref RawEmailBucket
          PO_BUCKET: !Ref POBucket
          INVOICE_BUCKET: !Ref InvoiceBucket
          HOLDEN_JSON_BUCKET: !Ref HoldenJsonBucket
          PO_TABLE: !Ref POTable
          COMPLETED_TABLE: !Ref CompletedTable

  # S3 Buckets
  RawEmailBucket:
    Type: AWS::S3::Bucket

  POBucket:
    Type: AWS::S3::Bucket

  InvoiceBucket:
    Type: AWS::S3::Bucket

  HoldenJsonBucket:
    Type: AWS::S3::Bucket

  # DynamoDB Tables
  POTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: po_table
      AttributeDefinitions:
        - AttributeName: po_number
          AttributeType: S
      KeySchema:
        - AttributeName: po_number
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CompletedTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Completed_Items
      AttributeDefinitions:
        - AttributeName: invoice_number
          AttributeType: S
      KeySchema:
        - AttributeName: invoice_number
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ProcessFileFunction:
    Description: Lambda function to process files
    Value: !GetAtt ProcessFileFunction.Arn
  RawEmailBucket:
    Description: Raw email S3 bucket name
    Value: !Ref RawEmailBucket
  POBucket:
    Description: PO S3 bucket name
    Value: !Ref POBucket
  InvoiceBucket:
    Description: Invoice S3 bucket name
    Value: !Ref InvoiceBucket
  HoldenJsonBucket:
    Description: Holden JSON S3 bucket name
    Value: !Ref HoldenJsonBucket
  POTable:
    Description: DynamoDB table for POs
    Value: !Ref POTable
  CompletedTable:
    Description: DynamoDB table for completed items
    Value: !Ref CompletedTable
